# Generated by Django 4.1.4 on 2023-03-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='totel',
            new_name='total',
        ),
    ]
